### PR TITLE
authentication with members only platform

### PR DESCRIPTION
**Pull request by jabichris**
## What does this PR do?

This PR is the work done on:
- Forms and Helpers
- Authentication and Authorisation

### CODE REVIEW

**Review by Ispirett — CHANGES_REQUESTED** [review]
## Status Required 
Hey! @jabichris  great work so far you have done well. :+1: 
There are some things to take care of below. 
- [x] As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Progress :clap: :clap:  However, some requirements need to be implemented in order to get approval for this project. Check :arrow_down: 

* [x] As a guest you can see only post's text ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
  - This applies on posts#show view also
* [x] As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
  - This applies to posts#index view also
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by jabichris** [comment]
Thank you for the feedback. I hope everything is fixed and I am requesting a re-review

**Review by rOluochKe — APPROVED** [review]
Hello @jabichris 
### You got it right this time :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next project.
- Happy coding!

**Pull request merged**
